#pragma once

/**
 * @file SyncContextPool.hpp
 * @brief C++ 同步上下文池 - 基于 RAII 和 std::promise/future 的高效实现
 * 
 * 这是一个 head-only 的 C++ 模板库，提供线程安全的同步上下文池管理。
 * 采用 RAII 思想自动管理资源生命周期，使用 std::promise/std::future 实现
 * 高效的请求 - 响应同步机制。
 * 
 * 设计理念:
 * - 替代 C 语言的 pthread_cond_t + mutex 组合
 * - 利用现代 C++ 的 RAII 机制确保异常安全
 * - 编译期配置最大化性能 (零运行时开销)
 * - 与现有 ObjectPool 基础设施无缝集成
 * 
 * @author Generated by cpunchline-hub
 * @date 2026-03-22
 */

#include <memory>
#include <mutex>
#include <condition_variable>
#include <future>
#include <chrono>
#include <cstdint>
#include <cstring>

#include "ObjectPool.hpp"

/// @brief 同步上下文数据结构
/// 用于在请求 - 响应模式存储数据、结果和同步机制
///
/// 支持任意类型 T，包括:
/// - 默认可构造类型 (int, struct 等)
/// - 可移动类型 (std::vector, std::string 等)
/// - 不可拷贝但可移动的类型
///
/// @tparam T 数据类型，需要满足 MoveConstructible 要求
template <typename T = void>
struct SyncContext
{
    using DataType = T;

    mutable std::mutex mutex;  ///< 保护 data 和 result 的互斥锁
    DataType data;             ///< 用户数据 (当 T != void 时)
    int result = -1;           ///< 执行结果：0=成功，-1=错误
    std::promise<int> promise; ///< 用于同步等待的 promise

    /// 默认构造函数 - 要求 T 默认可构造
    SyncContext() = default;

    /// 带初始值的构造函数
    /// @param initial_data 初始数据 (通过完美转发传递)
    template <typename U,
              typename = std::enable_if_t<std::is_constructible<T, U &&>::value>>
    explicit SyncContext(U &&initial_data) :
        data(std::forward<U>(initial_data))
    {
    }

    // 禁用拷贝构造和拷贝赋值 (因为 std::promise 不可拷贝)
    SyncContext(const SyncContext &) = delete;
    SyncContext &operator=(const SyncContext &) = delete;

    // 禁移动构造和移动赋值 (因为成员被 mutex 保护且地址敏感)
    SyncContext(SyncContext &&) = delete;
    SyncContext &operator=(SyncContext &&) = delete;

    /// 重置上下文状态以便复用
    /// 对于可移动类型，使用 move assignment 清空数据
    void Reset()
    {
        std::lock_guard<std::mutex> lock(mutex);
        if constexpr (std::is_default_constructible<T>::value)
        {
            // 如果 T 是默认可构造的，使用默认赋值
            data = T{};
        }
        else
        {
            // 如果 T 不是默认可构造的，使用 placement new 重建
            // 注意：这要求外部在 Borrow 时提供初始值
            result = -1;
            return;
        }
        result = -1;
        // promise 不能重置，需要重新创建
    }

    /// 设置数据 (支持移动语义)
    /// @param new_data 新数据 (通过完美转发传递)
    template <typename U>
    void SetData(U &&new_data)
    {
        std::lock_guard<std::mutex> lock(mutex);
        data = std::forward<U>(new_data);
    }

    /// 获取数据的 const 引用
    /// @return 数据的 const 引用
    const T &GetData() const
    {
        std::lock_guard<std::mutex> lock(mutex);
        return data;
    }

    /// 获取数据的可变引用
    /// @return 数据的可变引用
    T &GetData()
    {
        std::lock_guard<std::mutex> lock(mutex);
        return data;
    }

    /// 设置结果并通知等待者
    /// @param res 结果码 (0=成功，-1=错误)
    void SetResult(int res)
    {
        std::lock_guard<std::mutex> lock(mutex);
        result = res;
        promise.set_value(res);
    }

    /// 等待结果完成
    /// @param timeout_ms 超时时间 (毫秒), 0 表示无限等待
    /// @return 实际等待的结果值，超时返回 -ETIMEDOUT
    int Wait(uint32_t timeout_ms = 0)
    {
        auto future = promise.get_future();
        if (timeout_ms == 0)
        {
            future.wait();
            return result;
        }

        auto status = future.wait_for(std::chrono::milliseconds(timeout_ms));
        if (status == std::future_status::timeout)
        {
            return -ETIMEDOUT;
        }
        return result;
    }
};

/// void 特化版本 (不存储用户数据)
template <>
struct SyncContext<void>
{
    int result = -1;           ///< 执行结果：0=成功，-1=错误
    std::promise<int> promise; ///< 用于同步等待的 promise
    std::mutex mutex;          ///< 保护 result 的互斥锁

    /// 重置上下文状态以便复用
    void Reset()
    {
        std::lock_guard<std::mutex> lock(mutex);
        result = -1;
    }

    /// 设置结果并通知等待者
    void SetResult(int res)
    {
        std::lock_guard<std::mutex> lock(mutex);
        result = res;
        promise.set_value(res);
    }

    /// 等待结果完成
    /// @param timeout_ms 超时时间 (毫秒), 0 表示无限等待
    /// @return 实际等待的结果值，超时返回 -ETIMEDOUT
    int Wait(uint32_t timeout_ms = 0)
    {
        auto future = promise.get_future();
        if (timeout_ms == 0)
        {
            future.wait();
            return result;
        }

        auto status = future.wait_for(std::chrono::milliseconds(timeout_ms));
        if (status == std::future_status::timeout)
        {
            return -ETIMEDOUT;
        }
        return result;
    }
};

/// @brief RAII 守卫对象 - 自动管理同步上下文的生命周期
/// 从池中借用上下文并在析构时自动归还
template <typename T = void>
class SyncContextGuard
{
public:
    using ContextType = SyncContext<T>;
    using PoolType = ObjectPool<ContextType>;

    /// 构造函数 - 从池中借用上下文
    explicit SyncContextGuard(PoolType &pool) :
        pool_(pool), ctx_sptr_(nullptr)
    {
        ctx_sptr_ = pool_.Borrow();
        if (ctx_sptr_)
        {
            ctx_sptr_->Reset(); // 确保初始状态干净
        }
    }

    /// 析构函数 - 自动归还上下文到池中
    ~SyncContextGuard() noexcept
    {
        if (ctx_sptr_)
        {
            ctx_sptr_->Reset(); // 重置状态
            pool_.Return(ctx_sptr_);
        }
    }

    // 禁止拷贝和移动
    SyncContextGuard(const SyncContextGuard &) = delete;
    SyncContextGuard &operator=(const SyncContextGuard &) = delete;
    SyncContextGuard(SyncContextGuard &&) = delete;
    SyncContextGuard &operator=(SyncContextGuard &&) = delete;

    /// 获取底层上下文指针
    ContextType *get() const noexcept
    {
        return ctx_sptr_.get();
    }

    /// 解引用操作符
    ContextType &operator*() const noexcept
    {
        return *ctx_sptr_;
    }

    /// 箭头操作符
    ContextType *operator->() const noexcept
    {
        return ctx_sptr_.get();
    }

    /// 布尔转换 - 检查是否成功借用到上下文
    explicit operator bool() const noexcept
    {
        return ctx_sptr_.get() != nullptr;
    }

    /// 检查是否有效
    bool IsValid() const noexcept
    {
        return ctx_sptr_.get() != nullptr;
    }

protected:
    // 保护构造函数用于创建空 guard
    SyncContextGuard(PoolType &pool, bool) :
        pool_(pool), ctx_sptr_(nullptr)
    {
    }

private:
    PoolType &pool_;
    std::shared_ptr<ContextType> ctx_sptr_;
};

/// @brief 基于 ObjectPool 的同步实体池 C++ 实现
/// 使用 RAII 和 std::promise/std::future 实现高效的同步等待机制
///
/// 特点:
/// - 使用 ObjectPool (基于 std::shared_ptr)
/// - 支持运行时动态扩展（在达到 MaxCount 前）
/// - 支持超时等待获取对象
/// - 自动内存管理，无需手动分配/释放
///
/// @tparam T 数据类型 (void 表示不存储数据，仅用于同步)
/// @tparam MaxCount 池的最大容量 (运行时配置，非编译期常量)
template <typename T = void>
class SyncContextPool
{
public:
    using ContextType = SyncContext<T>;
    using GuardType = SyncContextGuard<T>;

    /// 默认构造函数
    /// @param init_count 初始对象数量 (默认 0)
    /// @param max_count 最大对象数量 (默认 DEFAULT_OBJECT_POOL_MAX_NUM)
    /// @param timeout_ms 借用超时时间 (毫秒，默认 DEFAULT_OBJECT_POOL_TIMEOUT)
    explicit SyncContextPool(
        size_t init_count = 0,
        size_t max_count = DEFAULT_OBJECT_POOL_MAX_NUM,
        size_t timeout_ms = DEFAULT_OBJECT_POOL_TIMEOUT) :
        pool_(init_count, max_count, timeout_ms)
    {
    }

    /// 禁止拷贝和移动
    SyncContextPool(const SyncContextPool &) = delete;
    SyncContextPool &operator=(const SyncContextPool &) = delete;
    SyncContextPool(SyncContextPool &&) = delete;
    SyncContextPool &operator=(SyncContextPool &&) = delete;

    /// 从池中借用一个同步上下文 (RAII 方式)
    /// @return GuardType RAII 守卫对象，自动管理生命周期
    GuardType Borrow()
    {
        return GuardType(pool_);
    }

    /// 尝试借用上下文 (不等待)
    /// @return std::unique_ptr<GuardType> 如果成功则包含有效上下文，否则为 nullptr
    std::unique_ptr<GuardType> TryBorrow()
    {
        // 使用 ObjectPool 的 TryBorrow (非阻塞)
        auto sptr = pool_.TryBorrow();
        if (!sptr)
        {
            return nullptr;
        }

        // 创建有效的 guard
        return std::make_unique<GuardType>(pool_);
    }

    /// 获取池的空闲数量
    size_t FreeCount() const
    {
        return const_cast<ObjectPool<ContextType> &>(pool_).IdleNum();
    }

    /// 获取已使用数量
    size_t UsedCount() const
    {
        return const_cast<ObjectPool<ContextType> &>(pool_).BorrowNum();
    }

    /// 获取池的总容量 (运行时值)
    size_t Capacity() const
    {
        return pool_._max_num;
    }

    /// 打印池状态 (调试用)
    void DumpState(const char *label = "SyncContextPool") const
    {
        std::printf("[%s] Total: %zu, Idle: %zu, Borrowed: %zu\n",
                    label,
                    const_cast<ObjectPool<ContextType> &>(pool_).ObjectNum(),
                    const_cast<ObjectPool<ContextType> &>(pool_).IdleNum(),
                    const_cast<ObjectPool<ContextType> &>(pool_).BorrowNum());
    }

private:
    ObjectPool<ContextType> pool_;
};

// ============================================================================
// 使用示例:
// ============================================================================
//
// // 示例 1: 无数据的纯同步上下文
// SyncContextPool<void, 16> pool;
// {
//     auto guard = pool.Borrow();
//     if (!guard.IsValid()) {
//         // 处理池满的情况
//         return;
//     }
//
//     // 使用 guard->data 访问数据
//     // 使用 guard->SetResult(0) 设置结果
//     // 使用 guard->Wait(3000) 等待结果 (3 秒超时)
// } // guard 析构时自动归还到池中
//
// // 示例 2: 携带数据的同步上下文
// struct MyData {
//     int id;
//     char buffer[256];
// };
// SyncContextPool<MyData, 32> data_pool;
// {
//     auto guard = data_pool.Borrow();
//     guard->data.id = 42;
//     std::strcpy(guard->data.buffer, "hello");
//
//     // ... 使用数据 ...
// } // 自动归还
//
// ============================================================================
